[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[main]]
  identifier = "skills"
  name = "Skills"
  url = "#skills-section"
  weight = 2
[[main]]
  identifier = "resume"
  name = "Resume"
  url = "#resume-section"
  weight = 3
[[main]]
  identifier = "articles"
  name = "Articles"
  url = "#blog-section"
  weight = 4
